import type { wordDatabase } from '@/data/word-data';

import type { DailyPuzzleKey } from './types';

export type WordCategory = keyof typeof wordDatabase;

export const CATALOG_CONTENT_SCHEMA_VERSION = 1;

/** Anchor day of the theme rotation — also the catalog release base. */
export const CATALOG_ROTATION_BASE = '2026-01-26';

export type ThemeSeed = {
	readonly themeId: string;
	readonly label: string;
	readonly explanation: string;
	readonly distractors: readonly [string, string, string];
	/** Word-data category the daily Caccia grid draws its extra words from. */
	readonly cacciaFill: WordCategory;
	readonly puzzleWords: Record<DailyPuzzleKey, readonly [string, string, string]>;
};

export const THEMES = [
	{
		themeId: 'theme-mercato',
		label: 'Mercato italiano',
		explanation: 'Tutte le parole richiamano banchi, prodotti e gesti tipici del mercato.',
		distractors: ['Cinema di quartiere', 'Montagna innevata', 'Viaggio spaziale'],
		cacciaFill: 'cibo',
		puzzleWords: {
			parola: ['SPESA', 'COSTA', 'SOLDI'],
			caccia: ['FRUTTA', 'BANCONE', 'VERDURA'],
			paroliere: ['MERCATO', 'CESTINO', 'VENDERE'],
			impiccato: ['POMODORO', 'FORMAGGIO', 'SALUMI'],
			anagrammi: ['MONETE', 'SCONTO', 'CLIENTE'],
		},
	},
	{
		themeId: 'theme-mare',
		label: 'Estate al mare',
		explanation: 'La sfida raccoglie parole da spiaggia, onde, sole e vacanze.',
		distractors: ['Biblioteca antica', 'Officina meccanica', 'Teatro lirico'],
		cacciaFill: 'natura',
		puzzleWords: {
			parola: ['BARCA', 'ISOLA', 'BAGNO'],
			caccia: ['OMBRELLONE', 'CONCHIGLIA', 'SCOGLIO'],
			paroliere: ['MAREA', 'VELIERO', 'SABBIA'],
			impiccato: ['BAGNINO', 'COSTUME', 'TRAMONTO'],
			anagrammi: ['MARINO', 'SPIAGGIA', 'VACANZA'],
		},
	},
	{
		themeId: 'theme-cucina',
		label: 'Cucina di casa',
		explanation: 'Ingredienti, utensili e profumi domestici legano ogni puzzle.',
		distractors: ['Stazione ferroviaria', 'Giardino segreto', 'Laboratorio chimico'],
		cacciaFill: 'cibo',
		puzzleWords: {
			parola: ['BRODO', 'BURRO', 'AGLIO'],
			caccia: ['MESTOLO', 'RICETTA', 'TAGLIERE'],
			paroliere: ['PENTOLA', 'FARINA', 'TEGAME'],
			impiccato: ['CROSTATA', 'RISOTTO', 'COLTELLO'],
			anagrammi: ['SAPORE', 'CUCINA', 'BOLLIRE'],
		},
	},
	{
		themeId: 'theme-scuola',
		label: 'Giornata di scuola',
		explanation: 'Ogni parola rimanda a lezioni, quaderni e vita in classe.',
		distractors: ['Foresta tropicale', 'Partita allo stadio', 'Mercato notturno'],
		cacciaFill: 'scuola',
		puzzleWords: {
			parola: ['ESAME', 'PENNA', 'CARTA'],
			caccia: ['QUADERNO', 'LAVAGNA', 'COMPITO'],
			paroliere: ['MATITA', 'LEZIONE', 'ASTUCCIO'],
			impiccato: ['INTERVALLO', 'MAESTRA', 'DIARIO'],
			anagrammi: ['CLASSE', 'SCUOLA', 'STUDIO'],
		},
	},
	{
		themeId: 'theme-viaggio',
		label: 'Viaggio in treno',
		explanation: 'Binari, partenze e biglietti costruiscono il filo comune.',
		distractors: ['Cena in famiglia', 'Museo egizio', 'Campo di grano'],
		cacciaFill: 'viaggio',
		puzzleWords: {
			parola: ['TRENO', 'METRO', 'CORSA'],
			caccia: ['VALIGIA', 'STAZIONE', 'BIGLIETTO'],
			paroliere: ['RITARDO', 'BINARIO', 'VAGONE'],
			impiccato: ['CAPOTRENO', 'FERMATA', 'CARROZZA'],
			anagrammi: ['ORARIO', 'ANDATA', 'RITORNO'],
		},
	},
	{
		themeId: 'theme-musica',
		label: 'Musica e ritmo',
		explanation: 'Strumenti, note e palco fanno da tema nascosto della sfida.',
		distractors: ['Pesca sul lago', 'Cantiere urbano', 'Cucina rustica'],
		cacciaFill: 'musica',
		puzzleWords: {
			parola: ['SUONO', 'CANTO', 'DISCO'],
			caccia: ['CHITARRA', 'PIANOFORTE', 'TAMBURO'],
			paroliere: ['MELODIA', 'ACCORDO', 'RITMO'],
			impiccato: ['ORCHESTRA', 'CANTANTE', 'SPARTITO'],
			anagrammi: ['CONCERTO', 'CANZONE', 'ARPEGGIO'],
		},
	},
	{
		themeId: 'theme-montagna',
		label: 'Montagna d\'inverno',
		explanation: 'Neve, rifugi e sentieri alti tengono insieme i cinque giochi.',
		distractors: ['Spiaggia affollata', 'Sala da ballo', 'Mercato del pesce'],
		cacciaFill: 'natura',
		puzzleWords: {
			parola: ['MONTE', 'VENTO', 'LEGNA'],
			caccia: ['RIFUGIO', 'SLITTA', 'VALANGA'],
			paroliere: ['CIASPOLE', 'NEVICA', 'GHIACCIO'],
			impiccato: ['TELEFERICA', 'SCARPONE', 'BORRACCIA'],
			anagrammi: ['VETTA', 'SENTIERO', 'PENDIO'],
		},
	},
	{
		themeId: 'theme-cinema',
		label: 'Serata al cinema',
		explanation: 'Schermo, poltrone e pellicole legano ogni parola nascosta.',
		distractors: ['Orto botanico', 'Cantiere navale', 'Fiera del libro'],
		cacciaFill: 'hobby',
		puzzleWords: {
			parola: ['ICONA', 'SERIE', 'EPICO'],
			caccia: ['SCHERMO', 'PELLICOLA', 'POLTRONA'],
			paroliere: ['REGISTA', 'TRAMA', 'FINALE'],
			impiccato: ['PROIEZIONE', 'POPCORN', 'SOTTOTITOLI'],
			anagrammi: ['ATTORE', 'TITOLI', 'COLONNA'],
		},
	},
	{
		themeId: 'theme-giardino',
		label: 'Giardino di casa',
		explanation: 'Semi, attrezzi e fioriture compongono il filo verde della sfida.',
		distractors: ['Sala operatoria', 'Studio radiofonico', 'Deposito ferroviario'],
		cacciaFill: 'natura',
		puzzleWords: {
			parola: ['PRATO', 'FIORE', 'VANGA'],
			caccia: ['POTATURA', 'CONCIME', 'SEMENZA'],
			paroliere: ['PETALO', 'RADICE', 'SIEPE'],
			impiccato: ['ANNAFFIATOIO', 'GIRASOLE', 'RASTRELLO'],
			anagrammi: ['GERMOGLIO', 'TERRICCIO', 'AIUOLA'],
		},
	},
	{
		themeId: 'theme-stadio',
		label: 'Partita allo stadio',
		explanation: 'Tifo, gol e spalti affollati guidano le parole di oggi.',
		distractors: ['Sala da tavola', 'Miniera abbandonata', 'Osservatorio astronomico'],
		cacciaFill: 'sport',
		puzzleWords: {
			parola: ['CAMPO', 'GIOCO', 'ARENA'],
			caccia: ['TRIBUNA', 'ARBITRO', 'PORTIERE'],
			paroliere: ['RIGORE', 'TIFOSO', 'FISCHIO'],
			impiccato: ['CAMPIONATO', 'ATTACCANTE', 'SPOGLIATOIO'],
			anagrammi: ['STADIO', 'PALLONE', 'SQUADRA'],
		},
	},
	{
		themeId: 'theme-citta',
		label: 'Città di notte',
		explanation: 'Insegne, lampioni e vie deserte fanno da sfondo comune.',
		distractors: ['Bosco di faggi', 'Casa di campagna', 'Molo dei pescatori'],
		cacciaFill: 'citta',
		puzzleWords: {
			parola: ['NOTTE', 'VILLA', 'CORSO'],
			caccia: ['LAMPIONE', 'SEMAFORO', 'VETRINA'],
			paroliere: ['PIAZZA', 'INSEGNA', 'VICOLO'],
			impiccato: ['MARCIAPIEDE', 'GRATTACIELO', 'TASSISTA'],
			anagrammi: ['QUARTIERE', 'PALAZZO', 'TRAFFICO'],
		},
	},
	{
		themeId: 'theme-bosco',
		label: 'Passeggiata nel bosco',
		explanation: 'Alberi, muschio e animali discreti collegano i cinque giochi.',
		distractors: ['Sala macchine', 'Piazza del mercato', 'Cabina telefonica'],
		cacciaFill: 'natura',
		puzzleWords: {
			parola: ['BOSCO', 'CERVO', 'FELCE'],
			caccia: ['MUSCHIO', 'GHIANDA', 'SENTIERO'],
			paroliere: ['TRONCO', 'RESINA', 'FOGLIAME'],
			impiccato: ['SOTTOBOSCO', 'CAPRIOLO', 'ABETAIA'],
			anagrammi: ['RADURA', 'RAMOSCELLO', 'LICHENE'],
		},
	},
	{
		themeId: 'theme-arte',
		label: 'Museo e pittura',
		explanation: 'Tele, pennelli e sale silenziose reggono il tema di oggi.',
		distractors: ['Fienile estivo', 'Palestra scolastica', 'Cabina di regia'],
		cacciaFill: 'hobby',
		puzzleWords: {
			parola: ['MARMO', 'STILE', 'VETRO'],
			caccia: ['PENNELLO', 'CORNICE', 'SCULTURA'],
			paroliere: ['PITTURA', 'BOZZETTO', 'COLORE'],
			impiccato: ['CAVALLETTO', 'AFFRESCO', 'RESTAURO'],
			anagrammi: ['GALLERIA', 'RITRATTO', 'PAESAGGIO'],
		},
	},
	{
		themeId: 'theme-caffe',
		label: 'Colazione al bar',
		explanation: 'Tazzine, banconi e profumi del mattino legano ogni parola.',
		distractors: ['Cava di marmo', 'Sala di lettura', 'Pista da sci'],
		cacciaFill: 'cibo',
		puzzleWords: {
			parola: ['CAFFE', 'TAZZA', 'DOLCE'],
			caccia: ['CORNETTO', 'ZUCCHERO', 'BRIOCHE'],
			paroliere: ['SCHIUMA', 'TAZZINA', 'BANCONE'],
			impiccato: ['CAPPUCCINO', 'MACCHIATO', 'SPREMUTA'],
			anagrammi: ['BARISTA', 'COLAZIONE', 'RISTRETTO'],
		},
	},
	{
		themeId: 'theme-fattoria',
		label: 'Vita in fattoria',
		explanation: 'Stalle, campi arati e animali domestici formano il filo comune.',
		distractors: ['Metropolitana affollata', 'Sala congressi', 'Nave da crociera'],
		cacciaFill: 'animali',
		puzzleWords: {
			parola: ['MUCCA', 'CAPRA', 'GRANO'],
			caccia: ['TRATTORE', 'FIENILE', 'GALLINA'],
			paroliere: ['STALLA', 'RECINTO', 'ARATRO'],
			impiccato: ['CONTADINO', 'PAGLIAIO', 'MUNGITURA'],
			anagrammi: ['RACCOLTO', 'PASCOLO', 'GRANAIO'],
		},
	},
	{
		themeId: 'theme-officina',
		label: 'Officina e mestieri',
		explanation: 'Attrezzi, olio e mani sporche tengono unita la sfida.',
		distractors: ['Sala da concerto', 'Spiaggia deserta', 'Aula magna'],
		cacciaFill: 'trasporti',
		puzzleWords: {
			parola: ['FERRO', 'FUOCO', 'SALDO'],
			caccia: ['MARTELLO', 'CACCIAVITE', 'TENAGLIA'],
			paroliere: ['CHIAVE', 'BULLONE', 'MORSA'],
			impiccato: ['SALDATRICE', 'INGRANAGGIO', 'CARBURATORE'],
			anagrammi: ['MOTORE', 'ATTREZZO', 'RIPARARE'],
		},
	},
	{
		themeId: 'theme-natale',
		label: 'Feste di Natale',
		explanation: 'Luci, regali e tavolate d\'inverno collegano ogni gioco.',
		distractors: ['Corsa campestre', 'Cantina buia', 'Studio dentistico'],
		cacciaFill: 'famiglia',
		puzzleWords: {
			parola: ['FESTA', 'DOLCI', 'TORTA'],
			caccia: ['PRESEPE', 'GHIRLANDA', 'CANDELA'],
			paroliere: ['REGALO', 'ABETE', 'LUCINE'],
			impiccato: ['PANETTONE', 'TOMBOLATA', 'ADDOBBI'],
			anagrammi: ['CENONE', 'RENNA', 'CAMINETTO'],
		},
	},
	{
		themeId: 'theme-biblioteca',
		label: 'Biblioteca silenziosa',
		explanation: 'Scaffali, pagine e silenzio guidano le parole nascoste.',
		distractors: ['Sala giochi', 'Porto commerciale', 'Serra tropicale'],
		cacciaFill: 'scuola',
		puzzleWords: {
			parola: ['LEGGE', 'CALMA', 'FRASE'],
			caccia: ['SCAFFALE', 'ROMANZO', 'LETTURA'],
			paroliere: ['PAGINA', 'INDICE', 'SILENZIO'],
			impiccato: ['SEGNALIBRO', 'BIBLIOTECA', 'CATALOGO'],
			anagrammi: ['VOLUME', 'PRESTITO', 'COPERTINA'],
		},
	},
	{
		themeId: 'theme-temporale',
		label: 'Cielo e temporale',
		explanation: 'Nuvole, tuoni e pioggia battente reggono il tema di oggi.',
		distractors: ['Sala prove', 'Mercato dei fiori', 'Rifugio alpino'],
		cacciaFill: 'tempo',
		puzzleWords: {
			parola: ['LAMPO', 'PIOVE', 'OMBRA'],
			caccia: ['OMBRELLO', 'GRANDINE', 'NUVOLA'],
			paroliere: ['TUONO', 'PIOGGIA', 'VENTATA'],
			impiccato: ['FULMINE', 'ACQUAZZONE', 'BURRASCA'],
			anagrammi: ['TEMPORALE', 'ARCOBALENO', 'ROVESCIO'],
		},
	},
	{
		themeId: 'theme-ospedale',
		label: 'Corsia d\'ospedale',
		explanation: 'Camici, visite e attese silenziose collegano i cinque giochi.',
		distractors: ['Sala da ballo liscio', 'Officina navale', 'Vigneto assolato'],
		cacciaFill: 'corpo',
		puzzleWords: {
			parola: ['LETTO', 'CUORE', 'ESITO'],
			caccia: ['BARELLA', 'SIRINGA', 'CAMICE'],
			paroliere: ['CORSIA', 'VISITA', 'REPARTO'],
			impiccato: ['INFERMIERA', 'TERMOMETRO', 'AMBULANZA'],
			anagrammi: ['MEDICO', 'DEGENZA', 'GUARIGIONE'],
		},
	},
	{
		themeId: 'theme-spazio',
		label: 'Viaggio nello spazio',
		explanation: 'Stelle, razzi e orbite lontane formano il filo comune.',
		distractors: ['Cantina del nonno', 'Fiera paesana', 'Salone da barbiere'],
		cacciaFill: 'tecnologia',
		puzzleWords: {
			parola: ['ASTRO', 'CIELO', 'SONDA'],
			caccia: ['PIANETA', 'COMETA', 'NAVETTA'],
			paroliere: ['ORBITA', 'GALASSIA', 'RAZZO'],
			impiccato: ['ASTRONAUTA', 'TELESCOPIO', 'SATELLITE'],
			anagrammi: ['STELLA', 'LANCIO', 'GRAVITA'],
		},
	},
	{
		themeId: 'theme-teatro',
		label: 'Sera a teatro',
		explanation: 'Sipario, platea e battute imparate legano ogni parola.',
		distractors: ['Campo da tennis', 'Panetteria di paese', 'Stazione spaziale'],
		cacciaFill: 'musica',
		puzzleWords: {
			parola: ['OPERA', 'SCENA', 'VOLTO'],
			caccia: ['SIPARIO', 'MASCHERA', 'PLATEA'],
			paroliere: ['BATTUTA', 'COPIONE', 'PALCO'],
			impiccato: ['APPLAUSO', 'PALCOSCENICO', 'COMMEDIA'],
			anagrammi: ['ATTRICE', 'PROVINO', 'DEBUTTO'],
		},
	},
	{
		themeId: 'theme-porto',
		label: 'Porto e pescatori',
		explanation: 'Reti, moli e barche al rientro reggono il tema nascosto.',
		distractors: ['Aula di chimica', 'Bosco innevato', 'Sala d\'attesa'],
		cacciaFill: 'trasporti',
		puzzleWords: {
			parola: ['CORDA', 'PESCE', 'TROTA'],
			caccia: ['PESCATORE', 'GABBIANO', 'ANCORA'],
			paroliere: ['RETINO', 'ORMEGGIO', 'BANCHINA'],
			impiccato: ['PESCHERECCIO', 'CASSETTA', 'TIMONIERE'],
			anagrammi: ['SALSEDINE', 'NASSA', 'RIMORCHIO'],
		},
	},
	{
		themeId: 'theme-vendemmia',
		label: 'Vendemmia d\'autunno',
		explanation: 'Filari, cesti colmi e mosto dolce collegano i cinque giochi.',
		distractors: ['Palestra affollata', 'Metro all\'alba', 'Studio televisivo'],
		cacciaFill: 'cibo',
		puzzleWords: {
			parola: ['VIGNA', 'TERRA', 'SUOLO'],
			caccia: ['GRAPPOLO', 'CANTINA', 'FILARE'],
			paroliere: ['MOSTO', 'POTARE', 'TINOZZA'],
			impiccato: ['VENDEMMIA', 'DAMIGIANA', 'FERMENTO'],
			anagrammi: ['UVAGGIO', 'BOTTAIO', 'RACCOLTA'],
		},
	},
	{
		themeId: 'theme-ufficio',
		label: 'Giornata in ufficio',
		explanation: 'Scrivanie, riunioni e scadenze tengono insieme la sfida.',
		distractors: ['Spiaggia al tramonto', 'Grotta carsica', 'Circo itinerante'],
		cacciaFill: 'professioni',
		puzzleWords: {
			parola: ['TURNO', 'FIRMA', 'LISTA'],
			caccia: ['RIUNIONE', 'SCRIVANIA', 'AGENDA'],
			paroliere: ['TIMBRO', 'CARTELLA', 'VERBALE'],
			impiccato: ['SCADENZA', 'PRESENTAZIONE', 'ARCHIVIO'],
			anagrammi: ['COLLEGA', 'PROGETTO', 'RESOCONTO'],
		},
	},
	{
		themeId: 'theme-animali',
		label: 'Animali selvatici',
		explanation: 'Zanne, tane e savane lontane formano il filo comune.',
		distractors: ['Sartoria di lusso', 'Panificio all\'alba', 'Sala d\'incisione'],
		cacciaFill: 'animali',
		puzzleWords: {
			parola: ['TIGRE', 'LEONE', 'ZEBRA'],
			caccia: ['GHEPARDO', 'ELEFANTE', 'GIRAFFA'],
			paroliere: ['TANA', 'BRANCO', 'ZANNA'],
			impiccato: ['RINOCERONTE', 'COCCODRILLO', 'IPPOPOTAMO'],
			anagrammi: ['SAVANA', 'PREDATORE', 'CUCCIOLO'],
		},
	},
	{
		themeId: 'theme-moda',
		label: 'Vetrine di moda',
		explanation: 'Tessuti, sfilate e specchi lucidi legano ogni parola.',
		distractors: ['Rifugio di montagna', 'Cava di pietra', 'Sala macchinisti'],
		cacciaFill: 'vestiti',
		puzzleWords: {
			parola: ['GONNA', 'ABITO', 'PERLA'],
			caccia: ['SARTORIA', 'TESSUTO', 'CAMERINO'],
			paroliere: ['SFILATA', 'TAGLIA', 'BOTTONE'],
			impiccato: ['PASSERELLA', 'ACCESSORIO', 'STILISTA'],
			anagrammi: ['MODELLA', 'CUCITURA', 'GUARDAROBA'],
		},
	},
	{
		themeId: 'theme-panetteria',
		label: 'Forno e panetteria',
		explanation: 'Impasti, lievito e pane caldo reggono il tema di oggi.',
		distractors: ['Officina elettrica', 'Sala d\'aspetto', 'Campo da golf'],
		cacciaFill: 'cibo',
		puzzleWords: {
			parola: ['FORNO', 'PASTA', 'FARRO'],
			caccia: ['FOCACCIA', 'GRISSINO', 'CIABATTA'],
			paroliere: ['LIEVITO', 'CROSTA', 'IMPASTO'],
			impiccato: ['PANETTERIA', 'SFORNARE', 'MOLLICA'],
			anagrammi: ['FORNAIO', 'SEMOLA', 'PANIFICIO'],
		},
	},
	{
		themeId: 'theme-lago',
		label: 'Giornata al lago',
		explanation: 'Acque calme, canneti e barche a remi collegano i cinque giochi.',
		distractors: ['Deserto roccioso', 'Sala parto', 'Fabbrica tessile'],
		cacciaFill: 'natura',
		puzzleWords: {
			parola: ['LAGHI', 'PESCA', 'ACQUE'],
			caccia: ['CANOTTO', 'LIBELLULA', 'GIUNCO'],
			paroliere: ['SPONDA', 'CANNETO', 'REMARE'],
			impiccato: ['LUNGOLAGO', 'PONTILE', 'TRAGHETTO'],
			anagrammi: ['SPECCHIO', 'ANATRA', 'MULINELLO'],
		},
	},
	{
		themeId: 'theme-circo',
		label: 'Sotto il tendone',
		explanation: 'Trapezi, luci colorate e applausi guidano le parole nascoste.',
		distractors: ['Sala del catasto', 'Vigna in collina', 'Corsia autostradale'],
		cacciaFill: 'hobby',
		puzzleWords: {
			parola: ['CIRCO', 'PISTA', 'MAGIA'],
			caccia: ['TRAPEZIO', 'GIOCOLIERE', 'TENDONE'],
			paroliere: ['RULLO', 'CERCHIO', 'TENDA'],
			impiccato: ['PAGLIACCIO', 'ACROBATA', 'DOMATORE'],
			anagrammi: ['SPETTACOLO', 'TRUCCO', 'PARATA'],
		},
	},
] as const satisfies readonly ThemeSeed[];
