/**
 * Italian 5-letter words for Wordle Italiano
 * Extracted from word database and curated for gameplay
 */

import { validWords } from './wordle-valid-words.js';

export const wordleWords = [
  { word: 'GATTO', translation: 'cat', definition: 'A small domesticated feline, often kept as a pet' },
  { word: 'LEONE', translation: 'lion', definition: 'A large wild cat, known as the king of the jungle' },
  { word: 'TIGRE', translation: 'tiger', definition: 'A large striped wild cat native to Asia' },
  { word: 'VOLPE', translation: 'fox', definition: 'A cunning wild mammal with reddish fur and a bushy tail' },
  { word: 'PESCE', translation: 'fish', definition: 'An aquatic animal with gills and fins' },
  { word: 'MUCCA', translation: 'cow', definition: 'A large domesticated animal that produces milk' },
  { word: 'CAPRA', translation: 'goat', definition: 'A horned domesticated animal related to sheep' },
  { word: 'ASINO', translation: 'donkey', definition: 'A domesticated animal related to horses' },
  { word: 'POLLO', translation: 'chicken', definition: 'A common domesticated bird raised for eggs and meat' },
  { word: 'FALCO', translation: 'falcon', definition: 'A swift bird of prey used in falconry' },
  { word: 'CORVO', translation: 'crow', definition: 'A large black bird known for intelligence' },
  { word: 'CIGNO', translation: 'swan', definition: 'A large graceful waterbird with a long neck' },
  { word: 'TONNO', translation: 'tuna', definition: 'A large ocean fish' },
  { word: 'TROTA', translation: 'trout', definition: 'A freshwater fish' },
  { word: 'POLPO', translation: 'octopus', definition: 'A sea creature with eight tentacles' },
  { word: 'ROSPO', translation: 'toad', definition: 'An amphibian with dry warty skin' },
  { word: 'KOALA', translation: 'koala', definition: 'An Australian marsupial that eats eucalyptus' },
  { word: 'PANDA', translation: 'panda', definition: 'A black and white bear from China' },
  { word: 'ZEBRA', translation: 'zebra', definition: 'A striped horse-like African animal' },
  { word: 'CERVO', translation: 'deer', definition: 'A hoofed mammal with antlers' },
  { word: 'RENNA', translation: 'reindeer', definition: 'A deer from Arctic regions' },
  { word: 'LEPRE', translation: 'hare', definition: 'A fast-running mammal like a large rabbit' },
  { word: 'TALPA', translation: 'mole', definition: 'A small burrowing mammal' },
  { word: 'MOSCA', translation: 'fly', definition: 'A common flying insect' },
  { word: 'RAGNO', translation: 'spider', definition: 'An arachnid with eight legs' },
  { word: 'VESPA', translation: 'wasp', definition: 'A stinging insect similar to a bee' },
  { word: 'VERME', translation: 'worm', definition: 'A small elongated invertebrate' },
  { word: 'PIZZA', translation: 'pizza', definition: 'Italian flatbread topped with tomato sauce and cheese' },
  { word: 'PASTA', translation: 'pasta', definition: 'Italian noodles made from wheat flour' },
  { word: 'LATTE', translation: 'milk', definition: 'A white liquid produced by mammals to feed their young' },
  { word: 'CARNE', translation: 'meat', definition: 'The flesh of animals used as food' },
  { word: 'BURRO', translation: 'butter', definition: 'A dairy product made by churning cream' },
  { word: 'DOLCE', translation: 'dessert', definition: 'A sweet course typically eaten at the end of a meal' },
  { word: 'ACQUA', translation: 'water', definition: 'A clear liquid essential for life' },
  { word: 'PESCA', translation: 'peach', definition: 'A fuzzy-skinned sweet fruit' },
  { word: 'MANGO', translation: 'mango', definition: 'A tropical fruit with orange flesh' },
  { word: 'COCCO', translation: 'coconut', definition: 'A tropical fruit with hard shell and white flesh' },
  { word: 'AGLIO', translation: 'garlic', definition: 'A pungent bulb used for seasoning' },
  { word: 'FUNGO', translation: 'mushroom', definition: 'An edible fungus' },
  { word: 'COZZA', translation: 'mussel', definition: 'A dark-shelled shellfish' },
  { word: 'PANNA', translation: 'cream', definition: 'The fatty part of milk' },
  { word: 'TORTA', translation: 'cake', definition: 'A sweet baked dessert' },
  { word: 'MIELE', translation: 'honey', definition: 'A sweet substance made by bees' },
  { word: 'ACETO', translation: 'vinegar', definition: 'A sour liquid used for seasoning' },
  { word: 'ROSSO', translation: 'red', definition: 'The color of blood, fire, and ripe tomatoes' },
  { word: 'VERDE', translation: 'green', definition: 'The color of grass and leaves' },
  { word: 'VIOLA', translation: 'purple', definition: 'A color made by mixing red and blue' },
  { word: 'BEIGE', translation: 'beige', definition: 'A pale sandy yellow-brown color' },
  { word: 'LILLA', translation: 'lilac', definition: 'A light purple color' },
  { word: 'OLIVA', translation: 'olive', definition: 'A dark yellowish-green color' },
  { word: 'MENTA', translation: 'mint', definition: 'A pale green color' },
  { word: 'BOSCO', translation: 'forest green', definition: 'A dark green color' },
  { word: 'CIANO', translation: 'cyan', definition: 'A bright blue-green color' },
  { word: 'CAFFE', translation: 'coffee', definition: 'A dark brown color' },
  { word: 'PERLA', translation: 'pearl', definition: 'A lustrous white color' },
  { word: 'CREMA', translation: 'cream', definition: 'A pale yellowish-white color' },
  { word: 'AMBRA', translation: 'amber', definition: 'A golden-orange color' },
  { word: 'GIADA', translation: 'jade', definition: 'A green gemstone color' },
  { word: 'MALVA', translation: 'mauve', definition: 'A pale purple color' },
  { word: 'SCURO', translation: 'dark', definition: 'Having little or no light' },
  { word: 'OPACO', translation: 'dull', definition: 'Not shiny or bright' },
  { word: 'CALDO', translation: 'warm', definition: 'Having high temperature' },
  { word: 'MADRE', translation: 'mother', definition: 'A female parent' },
  { word: 'PADRE', translation: 'father', definition: 'A male parent' },
  { word: 'NONNO', translation: 'grandfather', definition: 'The father of one\'s parent' },
  { word: 'NONNA', translation: 'grandmother', definition: 'The mother of one\'s parent' },
  { word: 'MAMMA', translation: 'mom', definition: 'Informal word for mother' },
  { word: 'NUORA', translation: 'daughter-in-law', definition: 'The wife of one\'s son' },
  { word: 'EREDE', translation: 'heir', definition: 'A person who inherits' },
  { word: 'PROLE', translation: 'offspring', definition: 'The children of a person or animal' },
  { word: 'NONNI', translation: 'grandparents', definition: 'Parents of one\'s parents' },
  { word: 'FIGLI', translation: 'children', definition: 'Sons and daughters' },
  { word: 'TESTA', translation: 'head', definition: 'The upper part of the body containing the brain' },
  { word: 'BOCCA', translation: 'mouth', definition: 'The opening for eating and speaking' },
  { word: 'DENTE', translation: 'tooth', definition: 'A hard white structure in the mouth used for biting' },
  { word: 'COLLO', translation: 'neck', definition: 'The part connecting the head to the body' },
  { word: 'PETTO', translation: 'chest', definition: 'The front part of the upper body' },
  { word: 'CUORE', translation: 'heart', definition: 'The organ that pumps blood through the body' },
  { word: 'GAMBA', translation: 'leg', definition: 'The lower limb used for walking' },
  { word: 'PIEDE', translation: 'foot', definition: 'The end part of the leg used for standing' },
  { word: 'PELLE', translation: 'skin', definition: 'The outer covering of the body' },
  { word: 'IRIDE', translation: 'iris', definition: 'The colored part of the eye' },
  { word: 'MENTO', translation: 'chin', definition: 'The lowest part of the face' },
  { word: 'MILZA', translation: 'spleen', definition: 'An organ that filters blood' },
  { word: 'POLSO', translation: 'wrist', definition: 'The joint between hand and forearm' },
  { word: 'PALMO', translation: 'palm', definition: 'The inside of the hand' },
  { word: 'MEDIO', translation: 'middle finger', definition: 'The third digit of the hand' },
  { word: 'NOCCA', translation: 'knuckle', definition: 'A finger joint' },
  { word: 'NERVO', translation: 'nerve', definition: 'Fiber transmitting signals' },
  { word: 'AVERE', translation: 'to have', definition: 'To possess or own something' },
  { word: 'BUONO', translation: 'good', definition: 'Of high quality or morally right' },
  { word: 'BELLO', translation: 'beautiful', definition: 'Pleasing to the eye or mind' },
  { word: 'NUOVO', translation: 'new', definition: 'Recently made or acquired' },
  { word: 'BASSO', translation: 'short/low', definition: 'Of small vertical extent' },
  { word: 'LUNGO', translation: 'long', definition: 'Of great horizontal extent' },
  { word: 'CORTO', translation: 'short', definition: 'Of small horizontal extent' },
  { word: 'LENTO', translation: 'slow', definition: 'Moving or operating at low speed' },
  { word: 'FORTE', translation: 'strong', definition: 'Having great physical power' },
  { word: 'VENTO', translation: 'wind', definition: 'Moving air, especially a natural current' },
  { word: 'TUONO', translation: 'thunder', definition: 'The loud sound that follows lightning' },
  { word: 'GONNA', translation: 'skirt', definition: 'A garment hanging from the waist' },
  { word: 'JEANS', translation: 'jeans', definition: 'Casual pants made of denim' },
  { word: 'CUOCO', translation: 'cook/chef', definition: 'A person who prepares food professionally' },
  { word: 'TRENO', translation: 'train', definition: 'A connected series of rail cars' },
  { word: 'AEREO', translation: 'airplane', definition: 'A powered flying vehicle with wings' },
  { word: 'BARCA', translation: 'boat', definition: 'A small vessel for traveling on water' },
  { word: 'METRO', translation: 'subway', definition: 'An underground urban railway system' },
  { word: 'BAGNO', translation: 'bathroom', definition: 'A room with a toilet and sink' },
  { word: 'LETTO', translation: 'bed', definition: 'Furniture for sleeping' },
  { word: 'SEDIA', translation: 'chair', definition: 'Furniture for sitting on' },
  { word: 'PORTA', translation: 'door', definition: 'A hinged barrier for entering rooms' },
  { word: 'TETTO', translation: 'roof', definition: 'The top covering of a building' },
  { word: 'SCALA', translation: 'stairs', definition: 'Steps for going between floors' },
  { word: 'NUOTO', translation: 'swimming', definition: 'Moving through water using the body' },
  { word: 'CORSA', translation: 'running', definition: 'Moving quickly on foot as exercise or sport' },
  { word: 'RUGBY', translation: 'rugby', definition: 'A team sport similar to football' },
  { word: 'RITMO', translation: 'rhythm', definition: 'A pattern of beats in music' },
  { word: 'MOUSE', translation: 'mouse', definition: 'A pointing device for computers' },
  { word: 'EMAIL', translation: 'email', definition: 'Electronic mail sent via internet' },
  { word: 'VIDEO', translation: 'video', definition: 'Moving visual images recorded or displayed' },
  { word: 'ROBOT', translation: 'robot', definition: 'A programmable machine that performs tasks' },
  { word: 'PAURA', translation: 'fear', definition: 'An unpleasant emotion caused by threat' },
  { word: 'AMORE', translation: 'love', definition: 'A strong feeling of affection' },
  { word: 'GIOIA', translation: 'joy', definition: 'A feeling of great happiness' },
  { word: 'CALMO', translation: 'calm', definition: 'Peaceful and not agitated' },
  { word: 'NOTTE', translation: 'night', definition: 'Time between sunset and sunrise' },
  { word: 'SETTE', translation: 'seven', definition: 'The number 7' },
  { word: 'DIECI', translation: 'ten', definition: 'The number 10' },
  { word: 'VENTI', translation: 'twenty', definition: 'The number 20' },
  { word: 'CENTO', translation: 'hundred', definition: 'The number 100' },
  { word: 'MILLE', translation: 'thousand', definition: 'The number 1000' },
  { word: 'PONTE', translation: 'bridge', definition: 'A structure spanning a physical obstacle' },
  { word: 'PARCO', translation: 'park', definition: 'A public green space in a city' },
  { word: 'MUSEO', translation: 'museum', definition: 'A building displaying art or historical objects' },
  { word: 'BANCA', translation: 'bank', definition: 'A financial institution' },
  { word: 'FIORE', translation: 'flower', definition: 'The colorful part of a plant' },
  { word: 'FIUME', translation: 'river', definition: 'A large natural stream of water' },
  { word: 'CIELO', translation: 'sky', definition: 'The space above the earth' },
  { word: 'TERRA', translation: 'earth/ground', definition: 'The surface of the planet or soil' },
  { word: 'ISOLA', translation: 'island', definition: 'Land surrounded by water' },
  { word: 'VALLE', translation: 'valley', definition: 'A low area between hills or mountains' },
  { word: 'LIBRO', translation: 'book', definition: 'Written or printed pages bound together' },
  { word: 'PENNA', translation: 'pen', definition: 'A writing instrument using ink' },
  { word: 'GOMMA', translation: 'eraser', definition: 'A tool for removing pencil marks' },
  { word: 'ZAINO', translation: 'backpack', definition: 'A bag carried on the back' },
  { word: 'BANCO', translation: 'desk', definition: 'A table for students to work at' },
  { word: 'ESAME', translation: 'exam', definition: 'A formal test of knowledge' },
  { word: 'DANZA', translation: 'dance', definition: 'Moving rhythmically to music' },
  { word: 'CANTO', translation: 'singing', definition: 'Making music with the voice' },
  { word: 'TAZZA', translation: 'cup', definition: 'A small container with a handle for hot drinks' },
  { word: 'FORNO', translation: 'oven', definition: 'An enclosed compartment for baking' },
  { word: 'HOTEL', translation: 'hotel', definition: 'An establishment providing lodging' },
  { word: 'MAPPA', translation: 'map', definition: 'A diagram showing an area\'s layout' },
  { word: 'GUIDA', translation: 'guide', definition: 'A person who shows tourists around' }
];

export function getRandomWord() {
  const randomIndex = Math.floor(Math.random() * wordleWords.length);
  return wordleWords[randomIndex];
}

export function getDailyWord() {
  const today = new Date();
  const startDate = Date.UTC(2024, 0, 1);
  const todayUTC = Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate());
  const daysSinceStart = Math.floor((todayUTC - startDate) / (1000 * 60 * 60 * 24));
  const wordIndex = daysSinceStart % wordleWords.length;
  return wordleWords[wordIndex];
}

export function isValidWord(word) {
  return validWords.has(word.toUpperCase());
}
