import { StyleSheet } from 'react-native';

import { GameFonts, GamePalette } from '@/constants/game-theme';

export const styles = StyleSheet.create({
	safe: { flex: 1 },
	scroll: { flex: 1 },
	loadingCard: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },
	loadingTitle: { fontSize: 24, fontFamily: GameFonts.display800, marginBottom: 8, textAlign: 'center' },
	loadingCopy: { fontSize: 15, textAlign: 'center' },
	content: {
		flexGrow: 1,
		padding: 16,
		gap: 16,
		maxWidth: 640,
		width: '100%',
		alignSelf: 'center',
	},
	upper: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
	panel: {
		flex: 1,
		borderRadius: 24,
		borderWidth: 1,
		padding: 12,
		alignItems: 'center',
		gap: 8,
	},
	categoryPill: {
		backgroundColor: GamePalette.primaryLight,
		paddingVertical: 4,
		paddingHorizontal: 12,
		borderRadius: 99,
	},
	categoryText: {
		color: GamePalette.primary,
		fontSize: 11,
	fontFamily: GameFonts.body600,
		textTransform: 'uppercase',
		letterSpacing: 0.5,
	},
	statusColumn: { width: 118, gap: 12 },
	livesCard: {
		borderRadius: 20,
		borderWidth: 1,
		padding: 12,
		alignItems: 'center',
		gap: 8,
	},
	livesLabel: {
		fontSize: 10,
		fontFamily: GameFonts.body600,
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	hearts: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		justifyContent: 'center',
		gap: 4,
		maxWidth: 84,
	},
	heart: { fontSize: 18 },
	heartLost: { opacity: 0.35 },
	wordCard: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		justifyContent: 'center',
		rowGap: 10,
		columnGap: 7,
		borderRadius: 20,
		borderWidth: 1,
		padding: 18,
	},
	wordGap: { width: 16 },
	slot: {
		width: 30,
		height: 44,
		alignItems: 'center',
		justifyContent: 'center',
		borderBottomWidth: 3,
	},
	slotText: { fontSize: 22, fontFamily: GameFonts.display800, textTransform: 'uppercase' },
	keyboard: { marginTop: 'auto', gap: 7 },
	keyRow: { flexDirection: 'row', justifyContent: 'center', gap: 5 },
	key: {
		flex: 1,
		maxWidth: 56,
		height: 48,
		borderRadius: 8,
		borderWidth: 1,
		alignItems: 'center',
		justifyContent: 'center',
	},
	keyCorrect: { backgroundColor: GamePalette.success, borderColor: GamePalette.success },
	keyFaded: { opacity: 0.5 },
	keyPressed: { transform: [{ translateY: 2 }], opacity: 0.9 },
	keyText: { fontSize: 16, fontFamily: GameFonts.display700 },
	answerCard: {
		alignSelf: 'stretch',
		borderRadius: 20,
		borderWidth: 1,
		padding: 20,
		alignItems: 'center',
		marginTop: 4,
	},
	answerLabel: {
		fontSize: 11,
		fontFamily: GameFonts.body600,
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	answerWord: {
		fontSize: 32,
		fontFamily: GameFonts.display800,
		color: GamePalette.primary,
		marginVertical: 6,
		textAlign: 'center',
	},
	answerTranslation: { fontSize: 15, fontFamily: GameFonts.body700, marginBottom: 6 },
	answerDefinition: { fontSize: 13, fontStyle: 'italic', textAlign: 'center' },
});
