import { writeFileSync } from 'node:fs';

/**
 * Regenerates the bundled Paroliere lexicon from napolux/paroleitaliane (MIT).
 * Run with `bun run generate:dictionary` after bumping SOURCE_URL.
 *
 * The source is already accent-free ASCII, which is exactly the shape
 * `normalizeWord` produces, so entries need only uppercasing.
 */
const SOURCE_URL = 'https://raw.githubusercontent.com/napolux/paroleitaliane/master/paroleitaliane/280000_parole_italiane.txt';

/** A 4x4 board cannot realistically be traced past 10 letters, and 11+ forms would nearly double the bundle. */
const MIN_LENGTH = 3;
const MAX_LENGTH = 10;

const response = await fetch(SOURCE_URL);
if (!response.ok) throw new Error(`dictionary source responded ${response.status}`);

const words = [
	...new Set(
		(await response.text())
			.split('\n')
			.map((line) => line.trim().toUpperCase())
			.filter((word) => word.length >= MIN_LENGTH && word.length <= MAX_LENGTH && /^[A-Z]+$/.test(word)),
	),
].sort();

if (words.length < 100_000) throw new Error(`dictionary source yielded only ${words.length} words`);

const target = new URL('../src/data/italian-words.ts', import.meta.url);
writeFileSync(
	target,
	`// GENERATED by scripts/generate-italian-dictionary.ts — do not edit by hand.
// Source: napolux/paroleitaliane (MIT), ${MIN_LENGTH}-${MAX_LENGTH} letter forms, uppercased and accent-free.
// ${words.length.toLocaleString('en-US')} words.

/** Newline-delimited so the bundle carries one string literal instead of ${words.length.toLocaleString('en-US')} array entries. */
export const ITALIAN_WORD_BLOB = \`${words.join('\n')}\`;
`,
);

console.log(`wrote ${words.length} words to src/data/italian-words.ts`);
